
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 17 18:08:13 CST 2019
//----------------------------------------------------

package Analizador.E5;

import java_cup.runtime.*;
import Analizador.util.*;
import intefaz.Principal;
import java.util.Stack;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Aug 17 18:08:13 CST 2019
  */
public class ParserE5 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserE5() {super();}

  /** Constructor which sets the default scanner. */
  public ParserE5(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserE5(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\003\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\005\000\002\004\003" +
    "\000\002\005\003\000\002\005\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\006\010\006\021\005\001\002\000\006\002" +
    "\001\004\017\001\002\000\012\002\ufffb\004\ufffb\007\ufffb" +
    "\011\ufffb\001\002\000\006\010\006\021\005\001\002\000" +
    "\004\002\014\001\002\000\012\002\ufffc\004\ufffc\007\ufffc" +
    "\011\ufffc\001\002\000\012\002\ufffe\004\ufffe\007\012\011" +
    "\ufffe\001\002\000\006\010\006\021\005\001\002\000\012" +
    "\002\ufffd\004\ufffd\007\ufffd\011\ufffd\001\002\000\004\002" +
    "\000\001\002\000\006\004\017\011\016\001\002\000\012" +
    "\002\ufffa\004\ufffa\007\ufffa\011\ufffa\001\002\000\006\010" +
    "\006\021\005\001\002\000\012\002\uffff\004\uffff\007\012" +
    "\011\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\012\002\006\003\003\004\010\005\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\003\014" +
    "\004\010\005\007\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\012\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\017\005\007\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserE5$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserE5$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserE5$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automáticamente ante algún error sintactico.*/
    public void syntax_error(Symbol s){
        System.err.println("Error en la Línea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "
        +s.value + " no reconocido." );
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
        
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperación de
    getErrores().*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error en la Línea " + (s.right+1)+ "Columna "+(s.left+1)+". Identificador " +
        s.value + " no reconocido.");  
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
  
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserE5$actions {




  private final ParserE5 parser;

  /** Constructor */
  CUP$ParserE5$actions(ParserE5 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserE5$do_action(
    int                        CUP$ParserE5$act_num,
    java_cup.runtime.lr_parser CUP$ParserE5$parser,
    java.util.Stack            CUP$ParserE5$stack,
    int                        CUP$ParserE5$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserE5$result;

      /* select the action based on the action number */
      switch (CUP$ParserE5$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // C ::= par1 A par2 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).value;
		
Atributo5 atributo=(Atributo5)val;
if(atributo.getContador()%2==0){
//es par
RESULT=new Atributo5("("+atributo.getValor()+")",atributo.getContador()+1);
}else{
RESULT=atributo;
}

              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // C ::= entero 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
		RESULT=new Atributo5(val,0);
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // B ::= C 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
		RESULT=val;
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("B",2, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // B ::= B por C 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
                int valor=((Atributo5)a).getContador()+((Atributo5)b).getContador();
		RESULT=new Atributo5(((Atributo5)b).getValor()+"*"+((Atributo5)a).getValor(),
                        valor);
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("B",2, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // A ::= B 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
		RESULT=val;
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= A mas B 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
		RESULT=new Atributo5(((Atributo5)a).getValor()+"+"+((Atributo5)b).getValor(),
                        ((Atributo5)a).getContador()+((Atributo5)b).getContador());
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)).value;
		RESULT = start_val;
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.elementAt(CUP$ParserE5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserE5$parser.done_parsing();
          return CUP$ParserE5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // INICIO ::= A 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserE5$stack.peek()).value;
		Principal.escribirMensajeEnConsola(((Atributo5)a).getValor());
              CUP$ParserE5$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE5$stack.peek()), RESULT);
            }
          return CUP$ParserE5$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

