
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 18 11:53:28 CST 2019
//----------------------------------------------------

package Analizador.E8;

import java_cup.runtime.*;
import Analizador.util.*;
import intefaz.Principal;
import java.util.Stack;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Aug 18 11:53:28 CST 2019
  */
public class ParserE8 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserE8() {super();}

  /** Constructor which sets the default scanner. */
  public ParserE8(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserE8(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\003\000\002\002\004\000\002\003" +
    "\006\000\002\003\003\000\002\006\006\000\002\004\005" +
    "\000\002\004\005\000\002\004\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\020\006\021\005\001\002\000\004\002" +
    "\001\001\002\000\004\010\022\001\002\000\004\010\012" +
    "\001\002\000\004\002\011\001\002\000\010\002\ufffe\011" +
    "\ufffe\012\ufffe\001\002\000\004\002\000\001\002\000\010" +
    "\020\006\021\005\022\015\001\002\000\006\011\ufff9\012" +
    "\ufff9\001\002\000\006\011\016\012\017\001\002\000\006" +
    "\011\ufffa\012\ufffa\001\002\000\010\002\uffff\011\uffff\012" +
    "\uffff\001\002\000\010\020\006\021\005\022\021\001\002" +
    "\000\006\011\ufffb\012\ufffb\001\002\000\006\011\ufffc\012" +
    "\ufffc\001\002\000\010\020\006\021\005\022\015\001\002" +
    "\000\006\011\024\012\017\001\002\000\010\002\ufffd\011" +
    "\ufffd\012\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\010\002\006\003\003\006\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\012\004\013\006\007\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\017\006\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\012\004\022\006\007\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserE8$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserE8$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserE8$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automáticamente ante algún error sintactico.*/
    public void syntax_error(Symbol s){
        System.err.println("Error en la Línea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "
        +s.value + " no reconocido." );
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
        
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperación de
    getErrores().*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error en la Línea " + (s.right+1)+ "Columna "+(s.left+1)+". Identificador " +
        s.value + " no reconocido.");  
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
  
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserE8$actions {




  private final ParserE8 parser;

  /** Constructor */
  CUP$ParserE8$actions(ParserE8 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserE8$do_action(
    int                        CUP$ParserE8$act_num,
    java_cup.runtime.lr_parser CUP$ParserE8$parser,
    java.util.Stack            CUP$ParserE8$stack,
    int                        CUP$ParserE8$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserE8$result;

      /* select the action based on the action number */
      switch (CUP$ParserE8$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // V ::= A 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		
if(val!=null){
ArrayList<Atributo> lista = new ArrayList<>();
lista.add((Atributo)val);
RESULT=lista;
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("V",2, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // V ::= id 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		
ArrayList<Atributo> lista = new ArrayList<>();
lista.add(new Atributo(val,'I'));
RESULT=lista;

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("V",2, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // V ::= V coma A 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		
if(l!=null && val!=null){
ArrayList<Atributo> lista = (ArrayList<Atributo>)l;
lista.add((Atributo)val);
RESULT=lista;
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("V",2, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // V ::= V coma id 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		
if(l!=null && val!=null){
ArrayList<Atributo> lista = (ArrayList<Atributo>)l;
lista.add(new Atributo(val,'I'));
RESULT=lista;
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("V",2, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // B ::= pr_mul par1 V par2 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).value;
		
if(l!=null){
ArrayList<Atributo> lista = (ArrayList<Atributo>)l;
if(lista.size()>1){
StringBuilder cadena = new StringBuilder();
int i;
for(i=0;i<lista.size();i++){
if(lista.get(i).getTipo()=='S'){
cadena.append("(");
}
cadena.append(lista.get(i).getCadena());
if(lista.get(i).getTipo()=='S'){
cadena.append(")");
}
if(i<lista.size()-1){
cadena.append("*");
}
}
RESULT=new Atributo(cadena.toString(),'M');
}
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("B",4, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-3)), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // A ::= B 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		if(val!=null){
RESULT=val;
}
              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= pr_sum par1 V par2 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).value;
		
if(l!=null){
ArrayList<Atributo> lista = (ArrayList<Atributo>)l;
if(lista.size()>1){
StringBuilder cadena = new StringBuilder();
int i;
for(i=0;i<lista.size();i++){
if(lista.get(i).getTipo()=='M'){
cadena.append("(");
}
cadena.append(lista.get(i).getCadena());
if(lista.get(i).getTipo()=='M'){
cadena.append(")");
}
if(i<lista.size()-1){
cadena.append("+");
}
}
RESULT=new Atributo(cadena.toString(),'S');
}
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-3)), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)).value;
		RESULT = start_val;
              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.elementAt(CUP$ParserE8$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserE8$parser.done_parsing();
          return CUP$ParserE8$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // INICIO ::= A 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE8$stack.peek()).value;
		
if(val!=null){
Atributo atributo=(Atributo)val;
Principal.escribirMensajeEnConsola(atributo.getCadena());
}else{
Principal.escribirMensajeEnConsola("Error");
}

              CUP$ParserE8$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE8$stack.peek()), RESULT);
            }
          return CUP$ParserE8$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

