
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 18 11:53:28 CST 2019
//----------------------------------------------------

package Analizador.E8;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pr_mul = 15;
  public static final int cadena = 19;
  public static final int par2 = 7;
  public static final int par1 = 6;
  public static final int decimal = 18;
  public static final int coma = 8;
  public static final int por = 5;
  public static final int booleano = 20;
  public static final int pr_sum = 14;
  public static final int caracter = 21;
  public static final int menos = 3;
  public static final int div = 4;
  public static final int EOF = 0;
  public static final int id = 16;
  public static final int error = 1;
  public static final int entero = 17;
  public static final int mas = 2;
  public static final int cor2 = 10;
  public static final int llave2 = 12;
  public static final int cor1 = 9;
  public static final int llave1 = 11;
  public static final int puntoycoma = 13;
}

