
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 08 16:17:06 CST 2019
//----------------------------------------------------

package Analizador.E18;

import java_cup.runtime.*;
import Analizador.util.*;
import intefaz.Principal;
import java.util.Stack;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Sep 08 16:17:06 CST 2019
  */
public class ParserE18 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserE18() {super();}

  /** Constructor which sets the default scanner. */
  public ParserE18(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserE18(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\003\000\002\002\004\000\002\004" +
    "\005\000\002\004\003\000\002\005\005\000\002\005\003" +
    "\000\002\006\003\000\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\006\010\006\023\004\001\002\000\012\002" +
    "\ufffb\004\ufffb\007\ufffb\011\ufffb\001\002\000\012\002\ufffc" +
    "\004\ufffc\007\ufffc\011\ufffc\001\002\000\006\010\006\023" +
    "\004\001\002\000\012\002\ufffe\004\ufffe\007\015\011\ufffe" +
    "\001\002\000\006\002\001\004\013\001\002\000\004\002" +
    "\012\001\002\000\004\002\000\001\002\000\006\010\006" +
    "\023\004\001\002\000\012\002\uffff\004\uffff\007\015\011" +
    "\uffff\001\002\000\006\010\006\023\004\001\002\000\012" +
    "\002\ufffd\004\ufffd\007\ufffd\011\ufffd\001\002\000\006\004" +
    "\013\011\020\001\002\000\012\002\ufffa\004\ufffa\007\ufffa" +
    "\011\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\012\002\010\004\007\005\006\006\004\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\004\016" +
    "\005\006\006\004\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\013" +
    "\006\004\001\001\000\002\001\001\000\004\006\015\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserE18$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserE18$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserE18$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automáticamente ante algún error sintactico.*/
    public void syntax_error(Symbol s){
        System.err.println("Error en la Línea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "
        +s.value + " no reconocido." );
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
        
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperación de
    getErrores().*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error en la Línea " + (s.right+1)+ "Columna "+(s.left+1)+". Identificador " +
        s.value + " no reconocido.");  
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
  
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserE18$actions {




  private final ParserE18 parser;

  /** Constructor */
  CUP$ParserE18$actions(ParserE18 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserE18$do_action(
    int                        CUP$ParserE18$act_num,
    java_cup.runtime.lr_parser CUP$ParserE18$parser,
    java.util.Stack            CUP$ParserE18$stack,
    int                        CUP$ParserE18$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserE18$result;

      /* select the action based on the action number */
      switch (CUP$ParserE18$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // T ::= par1 E par2 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).value;
		RESULT=val;
              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("T",4, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // T ::= entero 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		RESULT=new Atributo(val,"N");
              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("T",4, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // F ::= T 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		RESULT=val;
              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("F",3, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // F ::= F por T 
            {
              Object RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).right;
		Object izq = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).value;
		int derleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int derright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		Object der = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		
Atributo att = (Atributo)izq;
String nuevoValor="";
if(att.getOp().equals("+")){
nuevoValor="sum("+att.getValor()+")";
}else{
nuevoValor=att.getValor();
}
Atributo att2 = (Atributo)der;
if(att2.getOp().equals("+")){
nuevoValor+=",sum("+att2.getValor()+")";
}else{
nuevoValor+=","+att2.getValor();
}
RESULT=new Atributo(nuevoValor,"*");

              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("F",3, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // E ::= F 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		RESULT=val;
              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("E",2, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // E ::= E mas F 
            {
              Object RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).right;
		Object izq = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)).value;
		int derleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int derright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		Object der = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		
Atributo att = (Atributo)izq;
String nuevoValor="";
if(att.getOp().equals("*")){
nuevoValor="mul("+att.getValor()+")";
}else{
nuevoValor=att.getValor();
}
Atributo att2 = (Atributo)der;
if(att2.getOp().equals("*")){
nuevoValor+=",mul("+att2.getValor()+")";
}else{
nuevoValor+=","+att2.getValor();
}
RESULT=new Atributo(nuevoValor,"+");

              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("E",2, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-2)), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)).value;
		RESULT = start_val;
              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.elementAt(CUP$ParserE18$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserE18$parser.done_parsing();
          return CUP$ParserE18$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // INICIO ::= E 
            {
              Object RESULT =null;
		int izqleft = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).left;
		int izqright = ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()).right;
		Object izq = (Object)((java_cup.runtime.Symbol) CUP$ParserE18$stack.peek()).value;
		
Atributo att = (Atributo)izq;
String nuevoValor="";
if(att.getOp().equals("*")){
nuevoValor="mul("+att.getValor()+")";
}else if(att.getOp().equals("+")){
nuevoValor="sum("+att.getValor()+")";
}else{
nuevoValor=att.getValor();
}
Principal.escribirMensajeEnConsola(nuevoValor);

              CUP$ParserE18$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE18$stack.peek()), RESULT);
            }
          return CUP$ParserE18$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

