
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 08 15:36:50 CST 2019
//----------------------------------------------------

package Analizador.E17;

import java_cup.runtime.*;
import Analizador.util.*;
import intefaz.Principal;
import java.util.Stack;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Sep 08 15:36:50 CST 2019
  */
public class ParserE17 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserE17() {super();}

  /** Constructor which sets the default scanner. */
  public ParserE17(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserE17(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\004\000\002\003\003\000\002\003\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\006\030\007\031\005\001\002\000\010\002" +
    "\001\030\012\031\011\001\002\000\010\002\ufffc\030\ufffc" +
    "\031\ufffc\001\002\000\004\002\010\001\002\000\010\002" +
    "\ufffd\030\ufffd\031\ufffd\001\002\000\004\002\000\001\002" +
    "\000\010\002\ufffe\030\ufffe\031\ufffe\001\002\000\010\002" +
    "\uffff\030\uffff\031\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\010\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserE17$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserE17$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserE17$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automáticamente ante algún error sintactico.*/
    public void syntax_error(Symbol s){
        System.err.println("Error en la Línea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "
        +s.value + " no reconocido." );
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
        
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperación de
    getErrores().*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error en la Línea " + (s.right+1)+ "Columna "+(s.left+1)+". Identificador " +
        s.value + " no reconocido.");  
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
  
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserE17$actions {




  private final ParserE17 parser;

  /** Constructor */
  CUP$ParserE17$actions(ParserE17 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserE17$do_action(
    int                        CUP$ParserE17$act_num,
    java_cup.runtime.lr_parser CUP$ParserE17$parser,
    java.util.Stack            CUP$ParserE17$stack,
    int                        CUP$ParserE17$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserE17$result;

      /* select the action based on the action number */
      switch (CUP$ParserE17$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // A ::= uno 
            {
              Object RESULT =null;
		RESULT = "0";
              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          return CUP$ParserE17$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // A ::= cero 
            {
              Object RESULT =null;
		RESULT = "1";
              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          return CUP$ParserE17$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // A ::= A uno 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).value;
		RESULT =val+"0";
              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          return CUP$ParserE17$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= A cero 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).value;
		RESULT =val+"1";
              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          return CUP$ParserE17$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)).value;
		RESULT = start_val;
              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.elementAt(CUP$ParserE17$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserE17$parser.done_parsing();
          return CUP$ParserE17$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // INICIO ::= A 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE17$stack.peek()).value;
		
Principal.escribirMensajeEnConsola(val.toString());

              CUP$ParserE17$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE17$stack.peek()), RESULT);
            }
          return CUP$ParserE17$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

