
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 17 22:14:46 CST 2019
//----------------------------------------------------

package Analizador.E7;

import java_cup.runtime.*;
import Analizador.util.*;
import intefaz.Principal;
import java.util.Stack;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Aug 17 22:14:46 CST 2019
  */
public class ParserE7 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserE7() {super();}

  /** Constructor which sets the default scanner. */
  public ParserE7(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserE7(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\003\000\002\002\004\000\002\004" +
    "\004\000\002\004\004\000\002\004\004\000\002\004\003" +
    "\000\002\004\003\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\012\000\010\010\006\011\005\020\010\001\002\000" +
    "\012\002\001\010\013\011\012\020\014\001\002\000\012" +
    "\002\ufffa\010\ufffa\011\ufffa\020\ufffa\001\002\000\012\002" +
    "\ufffb\010\ufffb\011\ufffb\020\ufffb\001\002\000\004\002\011" +
    "\001\002\000\012\002\ufffc\010\ufffc\011\ufffc\020\ufffc\001" +
    "\002\000\004\002\000\001\002\000\012\002\ufffd\010\ufffd" +
    "\011\ufffd\020\ufffd\001\002\000\012\002\ufffe\010\ufffe\011" +
    "\ufffe\020\ufffe\001\002\000\012\002\uffff\010\uffff\011\uffff" +
    "\020\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\012\000\006\002\006\004\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserE7$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserE7$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserE7$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**Metodo al que se llama automáticamente ante algún error sintactico.*/
    public void syntax_error(Symbol s){
        System.err.println("Error en la Línea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "
        +s.value + " no reconocido." );
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
        
    }

    /**Metodo al que se llama en el momento en que ya no es posible una recuperación de
    getErrores().*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("Error en la Línea " + (s.right+1)+ "Columna "+(s.left+1)+". Identificador " +
        s.value + " no reconocido.");  
        Analizador.AnalizadorLenguaje.getErrores().add(new MiError("identificador \""+s.value+"\" no identificado", TipoError.SINTACTICO, 
        "",(s.right+1), (s.left+1)));
  
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserE7$actions {




  private final ParserE7 parser;

  /** Constructor */
  CUP$ParserE7$actions(ParserE7 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserE7$do_action(
    int                        CUP$ParserE7$act_num,
    java_cup.runtime.lr_parser CUP$ParserE7$parser,
    java.util.Stack            CUP$ParserE7$stack,
    int                        CUP$ParserE7$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserE7$result;

      /* select the action based on the action number */
      switch (CUP$ParserE7$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // A ::= par2 
            {
              Object RESULT =null;
		RESULT=-1;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // A ::= par1 
            {
              Object RESULT =null;
		RESULT=1;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // A ::= id 
            {
              Object RESULT =null;
		RESULT=0;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // A ::= A par2 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).value;
		RESULT=(int)val-1;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // A ::= A par1 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).value;
		RESULT=(int)val+1;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= A id 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).value;
		RESULT=val;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("A",2, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)).value;
		RESULT = start_val;
              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.elementAt(CUP$ParserE7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserE7$parser.done_parsing();
          return CUP$ParserE7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // INICIO ::= A 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()).right;
		Object val = (Object)((java_cup.runtime.Symbol) CUP$ParserE7$stack.peek()).value;
		
if((int)val==0){
Principal.escribirMensajeEnConsola("Balanceada");
}else{
Principal.escribirMensajeEnConsola("No Balanceada");
}

              CUP$ParserE7$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserE7$stack.peek()), RESULT);
            }
          return CUP$ParserE7$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

